### PR TITLE
resolves #93 allow soft unsetting built-in attributes

### LINKED ISSUE #93: Unable to soft unset built-in attributes in Asciidoctor
Reading from #72, I suppose that providing `'!name' => '@'` in attributes should soft unset a built-in attribute in Asciidoctor, but in fact the result is the same as a hard unset. The `'-name' => ''` syntax only stops this extension from passing an attribute to Asciidoctor. Using `'name' => false` does a hard reset, too.

I guess the culprit is `Middleman::AsciiDoc::AsciiDocExtension#merge_attributes`, which seems to set the value of the hash to nil as long as the key starts or ends with a `!`. It also converts all falses to nils (Is there a reason to do this?).

### PR DESCRIPTION
**Pull request by FiveYellowMice**

### CODE REVIEW

**Comment by mojavelinux** [comment]
This looks really great. Thanks for including tests to verify the behavior.

The failures look unrelated. I'll look into what that's happening. Stay tuned.

**Comment by mojavelinux** [comment]
I fixed the broken tests. Can you rebase?

**Comment by mojavelinux** [comment]
For now, I had to disable the tests on JRuby due to dependency resolution problems. If you can upgrade the dependencies in a separate PR, perhaps we can get JRuby working again.

**Comment by FiveYellowMice** [comment]
Thanks! Rebase is done. All tests passed for me, but the CI doesn't seem to be triggering, will this be a problem?

**Comment by mojavelinux** [comment]
We'll need to switch away from Travis CI. But that's a separate issue. I'll proceed with the merge, then do that.

Thanks!

**Pull request merged**
