### PR TITLE
updated dependencies to use latest version of asciidoctor

### PR DESCRIPTION
**Pull request by drallgood**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I think we should use `~> 1.5.4` instead. wdyt? Do you feel strongly about the min requirement setting, or would the fuzzy match be sufficient for you.

**Comment by mojavelinux** [comment]
I'll update it after merge.

**Comment by drallgood** [comment]
hmm.. I prefer the min requirement, because it prevents issues when a project isn't updated as often.
But the fuzzy match is okay, too.

**Comment by mojavelinux** [comment]
While I'm fairly confident at this point that we'll keep the project up to date at least with Asciidoctor itself, I'm open to just removing the version all together since really it doesn't matter what version of Asciidoctor you use. Let's say 1.5.0 is the min, though.

**Comment by mojavelinux** [comment]
Done!

**Pull request merged**
